name: treinamento
description: "Aplicativo de Treinamento com Realidade Aumentada."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0

  path_provider: ^2.1.2

  # Ícones adicionais para iOS e Material Design
  cupertino_icons: ^1.0.8

  # Biblioteca para Realidade Aumentada
  sceneview_flutter: 0.0.1

  # Gerenciamento de estado
  provider: ^6.1.2

  # Fonte personalizada
  google_fonts: ^6.1.0

  # Implementação da RA
  ar_flutter_plugin: ^0.7.3

  # Banco de Dados
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/models/planta.glb
